# Generated by Django 5.0.7 on 2024-07-21 07:44

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titel", models.CharField(max_length=10)),
                ("beschreibung", models.CharField(max_length=200)),
            ],
            managers=[
                ("organisationen", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CodeKategorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titel", models.CharField(max_length=100)),
                ("beschreibung", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="thema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titel", models.CharField(max_length=200)),
                ("beschreibung", models.TextField()),
                ("kontakt", models.CharField(max_length=200)),
                (
                    "jahr_start",
                    models.IntegerField(default=2025, verbose_name="Jahr Start"),
                ),
                (
                    "jahr_ende",
                    models.IntegerField(default=2029, verbose_name="Jahr Ende"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusinessObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kuerzel", models.CharField(max_length=10)),
                ("titel", models.CharField(max_length=200, verbose_name="Titel")),
                ("beschreibung", models.TextField(verbose_name="Beschreibung")),
                (
                    "erstellt_am",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "aufwand_personen_tage_plan",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Aufwand Personentage",
                    ),
                ),
                (
                    "aufwand_tsd_chf_plan",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Aufwand tsd CHF",
                    ),
                ),
                (
                    "jahr_start",
                    models.IntegerField(default=2024, verbose_name="Jahr Start"),
                ),
                (
                    "jahr_ende",
                    models.IntegerField(default=2024, verbose_name="Jahr Ende"),
                ),
                (
                    "erstellt_von",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "vorgaenger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objective_manager_app.businessobject",
                    ),
                ),
                (
                    "typ",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objective_manager_app.code",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Handlungsfeld",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objective_manager_app.businessobject",),
        ),
        migrations.CreateModel(
            name="Massnahme",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objective_manager_app.businessobject",),
        ),
        migrations.CreateModel(
            name="Ziel",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objective_manager_app.businessobject",),
        ),
        migrations.AddField(
            model_name="code",
            name="kategorie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="objective_manager_app.codekategorie",
            ),
        ),
        migrations.CreateModel(
            name="PlanRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jahr", models.IntegerField(default=2024, verbose_name="Jahr")),
                ("monat", models.IntegerField()),
                ("soll_wert", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ist_wert", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "aufwand_personen_tage_plan",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Aufwand Personentage (geplant)",
                    ),
                ),
                (
                    "aufwand_chf_plan",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Aufwand tsd CHF (geplant)",
                    ),
                ),
                (
                    "aufwand_personen_tage_ist",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Aufwand Personentage (ist)",
                    ),
                ),
                (
                    "aufwand_tsd_chf_ist",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="AAufwand tsd CHF (ist)",
                    ),
                ),
                ("beschreibung", models.TextField(verbose_name="Beschreibung")),
                (
                    "erstellt_am",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "erstellt_von",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "objekt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objective_manager_app.businessobject",
                        verbose_name="Massnahme",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objective_manager_app.code",
                        verbose_name="Organisation",
                    ),
                ),
            ],
        ),
    ]
