# Generated by Django 5.0.7 on 2024-08-23 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuerzel', models.CharField(max_length=10)),
                ('titel', models.CharField(max_length=10)),
                ('beschreibung', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CodeKategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('beschreibung', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(max_length=200)),
                ('dienststelle', models.CharField(max_length=200)),
                ('bereich', models.CharField(max_length=200)),
                ('departement_kuerzel', models.CharField(max_length=200)),
                ('dienststelle_kuerzel', models.CharField(max_length=200)),
                ('bereich_kuerzel', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['departement_kuerzel', 'dienststelle'],
            },
        ),
        migrations.CreateModel(
            name='BusinessObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuerzel', models.CharField(max_length=10, verbose_name='Nummer')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('beschreibung', models.TextField(verbose_name='Beschreibung')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aufwand_personen_tage_plan', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aufwand Personentage')),
                ('aufwand_tsd_chf_plan', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aufwand tsd CHF')),
                ('jahr_start', models.IntegerField(default=2024, verbose_name='Jahr Start')),
                ('jahr_ende', models.IntegerField(default=2024, verbose_name='Jahr Ende')),
                ('anmerkung_initialisierung', models.TextField(blank=True, null=True, verbose_name='Pol. Vorstoss')),
                ('mess_groesse', models.CharField(blank=True, max_length=200, null=True, verbose_name='Messbarkeit')),
                ('erstellt_von', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('vorgaenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objective_manager_app.businessobject')),
            ],
        ),
        migrations.CreateModel(
            name='Handlungsfeld',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('objective_manager_app.businessobject',),
        ),
        migrations.CreateModel(
            name='Massnahme',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('objective_manager_app.businessobject',),
        ),
        migrations.CreateModel(
            name='Ziel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('objective_manager_app.businessobject',),
        ),
        migrations.CreateModel(
            name='BusinessObjectTyp',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('objective_manager_app.code',),
        ),
        migrations.CreateModel(
            name='NeuBestehend',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('objective_manager_app.code',),
        ),
        migrations.CreateModel(
            name='Rolle',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('objective_manager_app.code',),
        ),
        migrations.CreateModel(
            name='RueckmeldungMV',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('objective_manager_app.code',),
        ),
        migrations.AddField(
            model_name='code',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objective_manager_app.codekategorie'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=200, verbose_name='Vorname')),
                ('nachname', models.CharField(max_length=200, verbose_name='Nachname')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('telefon', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefon')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objective_manager_app.organisation')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nachname', 'vorname'],
            },
        ),
        migrations.CreateModel(
            name='MassnahmeOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bemerkungen', models.TextField(blank=True, max_length=500, null=True, verbose_name='Bemerkungen')),
                ('massnahme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objective_manager_app.businessobject')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objective_manager_app.organisation')),
                ('person', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='objective_manager_app.person')),
                ('rolle', models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='objective_manager_app.rolle')),
            ],
        ),
        migrations.AddField(
            model_name='businessobject',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typ', to='objective_manager_app.businessobjecttyp'),
        ),
        migrations.AddField(
            model_name='businessobject',
            name='bestehende_massnahme',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bestehende_massnahme', to='objective_manager_app.neubestehend', verbose_name='Bestehende/Neue Massnahme'),
        ),
        migrations.CreateModel(
            name='PlanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jahr', models.IntegerField(default=2024, verbose_name='Jahr')),
                ('monat', models.IntegerField()),
                ('rueckmeldung_mv', models.TextField(blank=True, null=True, verbose_name='Bemerkungen MV')),
                ('einhaltung_termin', models.BooleanField(default=False, verbose_name='Einhaltung Termin')),
                ('umsetzung_mv', models.TextField(blank=True, null=True, verbose_name='Umsetzung Geschäftsjahr')),
                ('bemerkungen_fgs', models.TextField(blank=True, null=True, verbose_name='Bemerkungen FGS')),
                ('bemerkungen_sp', models.TextField(blank=True, null=True, verbose_name='Bemerkungen FGS')),
                ('faellig_am', models.DateField(blank=True, null=True, verbose_name='Bemerkungen Schlüsselperson')),
                ('fortschritt', models.IntegerField(default=0, verbose_name='Zielerreichungsgrad (1-5)')),
                ('zufriedenheit', models.IntegerField(blank=True, null=True, verbose_name='Wie zufrieden sind die MV mit der Umsetzung der Massnahme (1-5)')),
                ('schwierigkeiten', models.IntegerField(blank=True, null=True, verbose_name='Schwierigkeiten (5-1)')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('verantwortlich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objective_manager_app.massnahmeorganisation', verbose_name='Massnahme')),
                ('bemerkungen_code_mv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objective_manager_app.rueckmeldungmv', verbose_name='Bemerkungen MV (codiert)')),
            ],
        ),
    ]
