# Generated by Django 5.0.7 on 2024-12-30 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kuerzel", models.CharField(max_length=10)),
                ("titel", models.CharField(max_length=10)),
                ("beschreibung", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="CodeKategorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titel", models.CharField(max_length=100)),
                ("beschreibung", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Kennzahl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titel", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "beschreibung",
                    models.TextField(max_length=2000, verbose_name="Beschreibung"),
                ),
                (
                    "thema",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Thema"
                    ),
                ),
                (
                    "unterthema",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Thema"
                    ),
                ),
                ("url", models.CharField(max_length=1000, verbose_name="URL")),
            ],
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departement", models.CharField(max_length=200)),
                ("dienststelle", models.CharField(max_length=200)),
                ("bereich", models.CharField(max_length=200)),
                ("departement_kuerzel", models.CharField(max_length=200)),
                ("dienststelle_kuerzel", models.CharField(max_length=200)),
                ("bereich_kuerzel", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["departement_kuerzel", "dienststelle"],
            },
        ),
        migrations.CreateModel(
            name="BusinessObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kuerzel", models.CharField(max_length=10)),
                ("titel", models.CharField(max_length=200, verbose_name="Titel")),
                ("beschreibung", models.TextField(verbose_name="Beschreibung")),
                (
                    "erstellt_am",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "aufwand_personen_tage_plan",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Aufwand Personentage",
                    ),
                ),
                (
                    "aufwand_tsd_chf_plan",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Aufwand tsd CHF",
                    ),
                ),
                (
                    "jahr_start",
                    models.IntegerField(default=2024, verbose_name="Jahr Start"),
                ),
                (
                    "jahr_ende",
                    models.IntegerField(default=2024, verbose_name="Jahr Ende"),
                ),
                (
                    "anmerkung_initialisierung",
                    models.TextField(
                        blank=True, null=True, verbose_name="Pol. Vorstoss"
                    ),
                ),
                (
                    "mess_groesse",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Messbarkeit",
                    ),
                ),
                (
                    "erstellt_von",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "vorgaenger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objective_manager_app.businessobject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Handlungsfeld",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objective_manager_app.businessobject",),
        ),
        migrations.CreateModel(
            name="Massnahme",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objective_manager_app.businessobject",),
        ),
        migrations.CreateModel(
            name="Ziel",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objective_manager_app.businessobject",),
        ),
        migrations.CreateModel(
            name="BusinessObjectTyp",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objective_manager_app.code",),
        ),
        migrations.CreateModel(
            name="Rolle",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objective_manager_app.code",),
        ),
        migrations.CreateModel(
            name="Wirkung",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objective_manager_app.code",),
        ),
        migrations.AddField(
            model_name="code",
            name="kategorie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="objective_manager_app.codekategorie",
            ),
        ),
        migrations.CreateModel(
            name="BusinessObjectKennzahl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kennzahlen_business_objects",
                        to="objective_manager_app.businessobject",
                    ),
                ),
                (
                    "kennzahl",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_objects_kennzahlen",
                        to="objective_manager_app.kennzahl",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vorname", models.CharField(max_length=200, verbose_name="Vorname")),
                ("nachname", models.CharField(max_length=200, verbose_name="Nachname")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=200, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "telefon",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Telefon"
                    ),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objective_manager_app.organisation",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nachname", "vorname"],
            },
        ),
        migrations.CreateModel(
            name="MassnahmeOrganisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bemerkungen",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Bemerkungen",
                    ),
                ),
                (
                    "massnahme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objective_manager_app.businessobject",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objective_manager_app.organisation",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objective_manager_app.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Strategie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titel", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "titel_kurz",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        null=True,
                        verbose_name="Kurztitel",
                    ),
                ),
                (
                    "gueltigkeit_jahr_start",
                    models.IntegerField(default=2025, verbose_name="Jahr Start"),
                ),
                (
                    "gueltigkeit_jahr_ende",
                    models.IntegerField(default=2029, verbose_name="Jahr Ende"),
                ),
                (
                    "planungs_frequenz_monate",
                    models.IntegerField(
                        default=12, verbose_name="Planungsfrequenz (Monate)"
                    ),
                ),
                (
                    "beschreibung_intern",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Beschreibung für Beteiligte",
                    ),
                ),
                (
                    "beschreibung_extern",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Beschreibung für Externe",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Einstellungen",
                    ),
                ),
                (
                    "home_image",
                    models.TextField(blank=True, null=True, verbose_name="Bildpfad"),
                ),
                (
                    "kontakt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objective_manager_app.person",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objective_manager_app.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jahr", models.IntegerField(default=2024, verbose_name="Jahr")),
                ("monat", models.IntegerField()),
                (
                    "beginn_datum",
                    models.DateField(blank=True, null=True, verbose_name="Beginn am"),
                ),
                (
                    "ende_datum",
                    models.DateField(blank=True, null=True, verbose_name="Fällig am"),
                ),
                (
                    "fortschritt_pzt_plan",
                    models.IntegerField(verbose_name="Zielerreichungsgrad (Soll, %)"),
                ),
                (
                    "fortschritt_pzt_ist",
                    models.IntegerField(
                        default=0, verbose_name="Zielerreichungsgrad (Ist, %)"
                    ),
                ),
                (
                    "aufwand_personen_tage_plan",
                    models.IntegerField(
                        default=20, verbose_name="Aufwand Personentage (Soll)"
                    ),
                ),
                (
                    "aufwand_personen_tage_ist",
                    models.IntegerField(
                        default=0, verbose_name="Aufwand Personentage (Ist)"
                    ),
                ),
                (
                    "aufwand_tsd_chf_plan",
                    models.IntegerField(
                        default=0, verbose_name="Aufwand tsd CHF (Soll)"
                    ),
                ),
                (
                    "aufwand_tsd_chf_ist",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Aufwand tsd CHF (Ist)",
                    ),
                ),
                (
                    "kommentar",
                    models.TextField(blank=True, null=True, verbose_name="Kommentar"),
                ),
                (
                    "erstellt_am",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "erstellt_von",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "objekt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objective_manager_app.businessobject",
                    ),
                ),
                (
                    "verantwortlich",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objective_manager_app.massnahmeorganisation",
                        verbose_name="Massnahme",
                    ),
                ),
                (
                    "strategie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objective_manager_app.strategie",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="businessobject",
            name="strategie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="objective_manager_app.strategie",
            ),
        ),
        migrations.CreateModel(
            name="StrategieDokument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titel_dokument",
                    models.TextField(max_length=200, verbose_name="Titel Dokument"),
                ),
                ("url_feld", models.URLField(max_length=500, verbose_name="Webseite")),
                (
                    "strategie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dokumente",
                        to="objective_manager_app.strategie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Thema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kuerzel", models.CharField(max_length=10, verbose_name="Kürzel")),
                ("ebene", models.IntegerField(default=1, verbose_name="Ebene")),
                ("titel", models.CharField(max_length=200)),
                ("beschreibung", models.TextField(max_length=1000)),
                ("sortierung", models.IntegerField(default=0)),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "erstellt_von",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vorgaenger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objective_manager_app.thema",
                    ),
                ),
                (
                    "wunschrichtung",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objective_manager_app.wirkung",
                        verbose_name="Erwünschte Wirkung",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="businessobject",
            name="typ",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="typ",
                to="objective_manager_app.businessobjecttyp",
            ),
        ),
        migrations.CreateModel(
            name="BusinessObjectThema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="themen_business_objects",
                        to="objective_manager_app.businessobject",
                    ),
                ),
                (
                    "thema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_objects_themen",
                        to="objective_manager_app.thema",
                    ),
                ),
                (
                    "wirkung",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objective_manager_app.wirkung",
                    ),
                ),
            ],
        ),
    ]
