# Generated by Django 5.0.7 on 2024-07-21 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("objective_manager_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="code",
            managers=[],
        ),
        migrations.RenameField(
            model_name="planrecord",
            old_name="ist_wert",
            new_name="ist_wert_erreicht_pzt",
        ),
        migrations.RenameField(
            model_name="planrecord",
            old_name="soll_wert",
            new_name="soll_wert_erreicht_pzt",
        ),
    ]
