# Generated by Django 5.0.7 on 2024-08-23 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wertung',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('objective_manager_app.code',),
        ),
        migrations.RemoveField(
            model_name='planrecord',
            name='monat',
        ),
        migrations.AlterField(
            model_name='planrecord',
            name='bemerkungen_code_mv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planrecord_bemerkungen_code_mv', to='objective_manager_app.rueckmeldungmv', verbose_name='Bemerkungen MV (codiert)'),
        ),
        migrations.AlterField(
            model_name='planrecord',
            name='bemerkungen_sp',
            field=models.TextField(blank=True, null=True, verbose_name='Bemerkungen SP'),
        ),
        migrations.AlterField(
            model_name='planrecord',
            name='einhaltung_termin',
            field=models.BooleanField(default=False, verbose_name='Termin wird eingehalten'),
        ),
        migrations.AlterField(
            model_name='planrecord',
            name='faellig_am',
            field=models.DateField(blank=True, null=True, verbose_name='Fällig am'),
        ),
        migrations.AlterField(
            model_name='planrecord',
            name='umsetzung_mv',
            field=models.TextField(blank=True, null=True, verbose_name='Was wurde im Berichtsjahr umgesetzt?'),
        ),
        migrations.AlterField(
            model_name='planrecord',
            name='fortschritt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planrecord_fortschritt', to='objective_manager_app.wertung', verbose_name='Zielerreichungsgrad (1-5)'),
        ),
        migrations.AlterField(
            model_name='planrecord',
            name='schwierigkeiten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planrecord_schwierigkeiten', to='objective_manager_app.wertung', verbose_name='Schwierigkeiten'),
        ),
        migrations.AlterField(
            model_name='planrecord',
            name='zufriedenheit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planrecord_zufriedenheit', to='objective_manager_app.wertung', verbose_name='Wie zufrieden sind die MV mit der Umsetzung der Massnahme'),
        ),
    ]
