# Generated by Django 5.0.7 on 2024-07-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objective_manager_app", "0002_alter_code_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="code",
            name="kuerzel",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
    ]
