# Generated by Django 5.0.7 on 2025-01-01 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective_manager_app', '0003_remove_businessobject_mess_groesse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessobject',
            name='jahr_ende',
            field=models.IntegerField(default=2025, verbose_name='Jahr Ende'),
        ),
        migrations.AlterField(
            model_name='businessobject',
            name='jahr_start',
            field=models.IntegerField(default=2025, verbose_name='Jahr Start'),
        ),
        migrations.AlterField(
            model_name='businessobject',
            name='strategie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategie_business_objects', to='objective_manager_app.strategie'),
        ),
        migrations.AlterField(
            model_name='businessobject',
            name='titel',
            field=models.CharField(max_length=500, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='kennzahl',
            name='unterthema',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unterthema'),
        ),
        migrations.AlterField(
            model_name='planrecord',
            name='jahr',
            field=models.IntegerField(default=2025, verbose_name='Jahr'),
        ),
        migrations.AlterField(
            model_name='strategie',
            name='gueltigkeit_jahr_ende',
            field=models.IntegerField(default=2030, verbose_name='Jahr Ende'),
        ),
        migrations.AlterField(
            model_name='strategie',
            name='gueltigkeit_jahr_start',
            field=models.IntegerField(default=2026, verbose_name='Jahr Start'),
        ),
    ]
