# Generated by Django 5.0.7 on 2024-07-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objective_manager_app", "0003_code_kuerzel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planrecord",
            name="aufwand_chf_plan",
            field=models.IntegerField(verbose_name="Aufwand tsd CHF (geplant)"),
        ),
        migrations.AlterField(
            model_name="planrecord",
            name="aufwand_personen_tage_ist",
            field=models.IntegerField(
                default=0, verbose_name="Aufwand Personentage (ist)"
            ),
        ),
        migrations.AlterField(
            model_name="planrecord",
            name="aufwand_personen_tage_plan",
            field=models.IntegerField(verbose_name="Aufwand Personentage (geplant)"),
        ),
        migrations.AlterField(
            model_name="planrecord",
            name="ist_wert_erreicht_pzt",
            field=models.IntegerField(verbose_name="Zielerreichungsgrad (Soll, %)"),
        ),
        migrations.AlterField(
            model_name="planrecord",
            name="soll_wert_erreicht_pzt",
            field=models.IntegerField(verbose_name="Zielerreichungsgrad (Soll, %)"),
        ),
    ]
