# Generated by Django 5.0.7 on 2024-08-24 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objective_manager_app", "0004_rename_massnahme_planrecord_massnahme"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusMassnahme",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objective_manager_app.code",),
        ),
        migrations.AddField(
            model_name="planrecord",
            name="status",
            field=models.ForeignKey(
                default=17,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="objective_manager_app.statusmassnahme",
                verbose_name="Status",
            ),
        ),
    ]
