# Generated by Django 5.0.7 on 2024-07-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objective_manager_app", "0004_alter_planrecord_aufwand_chf_plan_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planrecord",
            name="aufwand_chf_plan",
        ),
        migrations.AddField(
            model_name="planrecord",
            name="aufwand_tsd_chf_plan",
            field=models.IntegerField(
                default=100, verbose_name="Aufwand tsd CHF (Soll)"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="planrecord",
            name="aufwand_personen_tage_ist",
            field=models.IntegerField(
                default=0, verbose_name="Aufwand Personentage (Ist)"
            ),
        ),
        migrations.AlterField(
            model_name="planrecord",
            name="aufwand_personen_tage_plan",
            field=models.IntegerField(verbose_name="Aufwand Personentage (Soll)"),
        ),
        migrations.AlterField(
            model_name="planrecord",
            name="aufwand_tsd_chf_ist",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Aufwand tsd CHF (Ist)",
            ),
        ),
        migrations.AlterField(
            model_name="planrecord",
            name="ist_wert_erreicht_pzt",
            field=models.IntegerField(verbose_name="Zielerreichungsgrad (Ist, %)"),
        ),
    ]
