# Generated by Django 5.0.7 on 2024-07-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objective_manager_app", "0005_remove_planrecord_aufwand_chf_plan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departement", models.CharField(max_length=200)),
                ("bereich", models.CharField(max_length=200)),
                ("dienststelle", models.CharField(max_length=200)),
                ("departement_kuerzel", models.CharField(max_length=200)),
                ("bereich_kuerzel", models.CharField(max_length=200)),
                ("dienststelle_kuerzel", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vorname", models.CharField(max_length=200)),
                ("nachname", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("telefon", models.CharField(max_length=200)),
                ("organisation", models.CharField(max_length=200)),
                ("funktion", models.CharField(max_length=200)),
                ("beschreibung", models.TextField()),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="planrecord",
            name="organisation",
        ),
        migrations.AddField(
            model_name="businessobject",
            name="anmerkung_initialisierung",
            field=models.TextField(blank=True, null=True, verbose_name="Pol. Vorstoss"),
        ),
        migrations.AddField(
            model_name="businessobject",
            name="bestehende_massnahme",
            field=models.CharField(
                default=1, max_length=200, verbose_name="Bestehende Massnahme"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="businessobject",
            name="messbarkeit",
            field=models.CharField(
                default=1, max_length=200, verbose_name="Messbarkeit"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="planrecord",
            name="beschreibung",
            field=models.TextField(blank=True, null=True, verbose_name="Beschreibung"),
        ),
    ]
