# Generated by Django 5.0.7 on 2024-08-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objective_manager_app", "0005_statusmassnahme_planrecord_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planrecord",
            name="verantwortlich",
        ),
        migrations.AlterField(
            model_name="planrecord",
            name="rueckmeldung_mv",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Bemerkungen MV zu Fortschritt, Zufriedenheit und Schwierigkeiten",
            ),
        ),
    ]
