# Generated by Django 5.0.7 on 2024-08-24 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objective_manager_app", "0006_remove_planrecord_verantwortlich_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planrecord",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planrecord_organisation",
                to="objective_manager_app.organisation",
                verbose_name="Federführende Organisation",
            ),
        ),
        migrations.AddField(
            model_name="planrecord",
            name="verantwortlich",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planrecord_person",
                to="objective_manager_app.person",
                verbose_name="Massnahmenverantwortliche Person",
            ),
        ),
    ]
