# Generated by Django 5.0.7 on 2024-08-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "objective_manager_app",
            "0007_planrecord_organisation_planrecord_verantwortlich",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="planrecord",
            old_name="bemerkungen_code_mv",
            new_name="rueckmeldung_code_mv",
        ),
        migrations.RenameField(
            model_name="planrecord",
            old_name="bemerkungen_fgs",
            new_name="rueckmeldung_fgs",
        ),
        migrations.RenameField(
            model_name="planrecord",
            old_name="bemerkungen_sp",
            new_name="rueckmeldung_sp",
        ),
    ]
