# Generated by Django 5.0.7 on 2024-07-23 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("objective_manager_app", "0007_person_org"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="organisation",
        ),
    ]
