# Generated by Django 5.0.7 on 2024-07-23 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objective_manager_app", "0008_remove_person_organisation"),
    ]

    operations = [
        migrations.CreateModel(
            name="NeuBestehend",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objective_manager_app.businessobject",),
        ),
        migrations.CreateModel(
            name="Rolle",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objective_manager_app.businessobject",),
        ),
        migrations.RenameField(
            model_name="person",
            old_name="org",
            new_name="organisation",
        ),
        migrations.AddField(
            model_name="businessobject",
            name="kontakt_verantwortlich",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="objective_manager_app.person",
                verbose_name="Kontakt verantwortlich",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="MassnahmeOrganisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "massnahme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objective_manager_app.businessobject",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objective_manager_app.organisation",
                    ),
                ),
            ],
        ),
    ]
