# Generated by Django 5.0.7 on 2024-07-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "objective_manager_app",
            "0009_neubestehend_rolle_rename_org_person_organisation_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="beschreibung",
        ),
        migrations.RemoveField(
            model_name="person",
            name="funktion",
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(
                blank=True, max_length=200, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="nachname",
            field=models.CharField(max_length=200, verbose_name="Nachname"),
        ),
        migrations.AlterField(
            model_name="person",
            name="telefon",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Telefon"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="vorname",
            field=models.CharField(max_length=200, verbose_name="Vorname"),
        ),
    ]
