# Generated by Django 5.0.7 on 2024-08-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objective_manager_app", "0009_remove_planrecord_fortschritt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="code",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
