# Generated by Django 5.0.7 on 2024-08-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objective_manager_app", "0010_code_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planrecord",
            name="rueckmeldung_code_mv",
        ),
        migrations.AddField(
            model_name="planrecord",
            name="rueckmeldung_anderes",
            field=models.BooleanField(default=False, null=True, verbose_name="Anderes"),
        ),
        migrations.AddField(
            model_name="planrecord",
            name="rueckmeldung_anderes_text",
            field=models.TextField(default=False, null=True, verbose_name="Anderes"),
        ),
        migrations.AddField(
            model_name="planrecord",
            name="rueckmeldung_austausch",
            field=models.BooleanField(
                default=False,
                null=True,
                verbose_name="Austausch oder Beratung ist erwünscht",
            ),
        ),
        migrations.AddField(
            model_name="planrecord",
            name="rueckmeldung_neupriorisierung",
            field=models.BooleanField(
                default=False,
                null=True,
                verbose_name="Neupriorisierung von departemententalen Zielen",
            ),
        ),
        migrations.AddField(
            model_name="planrecord",
            name="rueckmeldung_pol_vorstoss",
            field=models.BooleanField(
                default=False,
                null=True,
                verbose_name="Politischer Vorstoss hat Auswirkungen auf die Massnahme",
            ),
        ),
        migrations.AddField(
            model_name="planrecord",
            name="rueckmeldung_schwierigkeiten",
            field=models.BooleanField(
                default=False,
                null=True,
                verbose_name="Umsetzung der Massnahme bereitet Schwierigkeiten",
            ),
        ),
    ]
