# Generated by Django 5.0.7 on 2024-07-25 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objective_manager_app", "0011_person_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Strategie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titel", models.CharField(max_length=200)),
                ("kontakt", models.CharField(max_length=200)),
                (
                    "gueltigkeit_jahr_start",
                    models.IntegerField(default=2025, verbose_name="Jahr Start"),
                ),
                (
                    "gueltigkeit_jahr_ende",
                    models.IntegerField(default=2029, verbose_name="Jahr Ende"),
                ),
                (
                    "planungs_frequenz_monate",
                    models.IntegerField(
                        default=12, verbose_name="Planungsfrequenz (Monate)"
                    ),
                ),
                (
                    "beschreibung_intern",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Beschreibung für Beteiligte",
                    ),
                ),
                (
                    "beschreibung_extern",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Beschreibung für Externe",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objective_manager_app.organisation",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="thema",
        ),
        migrations.AddField(
            model_name="planrecord",
            name="faellig_am",
            field=models.DateField(blank=True, null=True, verbose_name="Fällig am"),
        ),
        migrations.AlterField(
            model_name="businessobject",
            name="erstellt_von",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Erstellt von",
            ),
        ),
    ]
