# Generated by Django 5.0.7 on 2024-08-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "objective_manager_app",
            "0011_remove_planrecord_rueckmeldung_code_mv_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="planrecord",
            name="rueckmeldung_anderes_text",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Anderes"
            ),
        ),
    ]
