# Generated by Django 5.0.7 on 2024-07-25 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "objective_manager_app",
            "0012_strategie_delete_thema_planrecord_faellig_am_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="businessobject",
            name="strategie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="objective_manager_app.strategie",
            ),
        ),
    ]
