# Generated by Django 5.0.7 on 2024-07-26 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objective_manager_app", "0013_businessobject_strategie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessobject",
            name="strategie",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="objective_manager_app.strategie",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="strategie",
            name="kontakt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="objective_manager_app.person",
            ),
        ),
    ]
