# Generated by Django 5.0.7 on 2024-07-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objective_manager_app', '0014_alter_businessobject_strategie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessObjectTyp',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('objective_manager_app.code',),
        ),
        migrations.RemoveField(
            model_name='businessobject',
            name='kontakt_verantwortlich',
        ),
    ]
