# Generated by Django 5.0.7 on 2024-08-27 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective_manager_app', '0014_janein_zufriedenheit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planrecord',
            name='einhaltung_termin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planrecord_einhaltung_termin', to='objective_manager_app.janein', verbose_name='Termin wird eingehalten'),
        ),
    ]
