# Generated by Django 5.0.7 on 2024-08-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objective_manager_app', '0015_alter_planrecord_einhaltung_termin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planrecord',
            name='einhaltung_termin',
        ),
    ]
