# Generated by Django 5.0.7 on 2024-08-01 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective_manager_app', '0015_businessobjecttyp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessobject',
            name='messbarkeit',
        ),
        migrations.AlterField(
            model_name='businessobject',
            name='bestehende_massnahme',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bestehende_massnahme', to='objective_manager_app.neubestehend'),
        ),
        migrations.AlterField(
            model_name='businessobject',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typ', to='objective_manager_app.businessobjecttyp'),
        ),
    ]
