# Generated by Django 5.0.7 on 2024-08-02 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective_manager_app', '0016_remove_businessobject_messbarkeit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='massnahmeorganisation',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='objective_manager_app.person'),
        ),
    ]
