# Generated by Django 5.0.7 on 2024-08-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective_manager_app', '0017_planrecord_einhaltung_termin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planrecord',
            name='einhaltung_termin',
            field=models.BooleanField(blank=True, null=True, verbose_name='Termin wird eingehalten'),
        ),
    ]
