# Generated by Django 5.0.7 on 2024-10-22 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective_manager_app', '0018_alter_planrecord_einhaltung_termin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planrecord',
            old_name='zufriedenheit',
            new_name='zufriedenheit_umsetzung',
        ),
        migrations.RemoveField(
            model_name='planrecord',
            name='schwierigkeiten',
        ),
        migrations.AddField(
            model_name='planrecord',
            name='stand_umsetzung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planrecord_schwierigkeiten', to='objective_manager_app.wertung', verbose_name='Stand Umsetzung der Massnahme'),
        ),
        migrations.AlterField(
            model_name='planrecord',
            name='rueckmeldung_anderes_text',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Allgemeine Bemerkungen'),
        ),
    ]
