# Generated by Django 5.0.7 on 2024-10-22 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective_manager_app', '0019_rename_zufriedenheit_planrecord_zufriedenheit_umsetzung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='reihenfolge',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planrecord',
            name='einhaltung_termin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='einhaltung_termine_janein', to='objective_manager_app.janein', verbose_name='Termin wird eingehalten'),
        ),
    ]
