# Generated by Django 5.0.7 on 2024-08-03 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objective_manager_app', '0019_remove_planrecord_objekt_planrecord_massnahme_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planrecord',
            old_name='ist_wert_erreicht_pzt',
            new_name='fortschritt_pzt_ist',
        ),
        migrations.RenameField(
            model_name='planrecord',
            old_name='soll_wert_erreicht_pzt',
            new_name='fortschritt_pzt_plan',
        ),
    ]
