# Generated by Django 5.0.7 on 2024-10-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective_manager_app', '0020_code_reihenfolge_alter_planrecord_einhaltung_termin'),
    ]

    operations = [
        migrations.AddField(
            model_name='planrecord',
            name='messbarkeit_umsetzung',
            field=models.TextField(blank=True, null=True, verbose_name='Messbarkeit der Umsetzung der Massnahme'),
        ),
    ]
