# Generated by Django 5.0.7 on 2024-08-04 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective_manager_app', '0020_rename_ist_wert_erreicht_pzt_planrecord_fortschritt_pzt_ist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planrecord',
            old_name='massnahme',
            new_name='verantwortlich',
        ),
        migrations.AddField(
            model_name='planrecord',
            name='Strategie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='objective_manager_app.strategie'),
            preserve_default=False,
        ),
    ]
