# Generated by Django 5.0.7 on 2024-10-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective_manager_app', '0021_planrecord_messbarkeit_umsetzung'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planrecord',
            name='messbarkeit_umsetzung',
        ),
        migrations.AddField(
            model_name='planrecord',
            name='notizen_fgs',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Notizen FGS'),
        ),
    ]
