# Generated by Django 5.0.7 on 2024-10-29 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective_manager_app', '0022_remove_planrecord_messbarkeit_umsetzung_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planrecord',
            name='rueckmeldung_anderes',
        ),
        migrations.RemoveField(
            model_name='planrecord',
            name='rueckmeldung_anderes_text',
        ),
        migrations.RemoveField(
            model_name='planrecord',
            name='rueckmeldung_neupriorisierung',
        ),
        migrations.RemoveField(
            model_name='planrecord',
            name='rueckmeldung_pol_vorstoss',
        ),
        migrations.RemoveField(
            model_name='planrecord',
            name='rueckmeldung_schwierigkeiten',
        ),
        migrations.AlterField(
            model_name='planrecord',
            name='stand_umsetzung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planrecord_schwierigkeiten', to='objective_manager_app.wertung', verbose_name='Zielerreichungsgrad'),
        ),
        migrations.AlterField(
            model_name='planrecord',
            name='umsetzung_mv',
            field=models.TextField(blank=True, null=True, verbose_name='Kommentar zur Zielerreichung'),
        ),
    ]
