# Generated by Django 5.0.7 on 2024-08-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective_manager_app', '0022_rename_strategie_planrecord_strategie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planrecord',
            name='beschreibung',
        ),
        migrations.AddField(
            model_name='planrecord',
            name='kommentar',
            field=models.TextField(blank=True, null=True, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='planrecord',
            name='aufwand_personen_tage_plan',
            field=models.IntegerField(default=20, verbose_name='Aufwand Personentage (Soll)'),
        ),
        migrations.AlterField(
            model_name='planrecord',
            name='aufwand_tsd_chf_plan',
            field=models.IntegerField(default=0, verbose_name='Aufwand tsd CHF (Soll)'),
        ),
        migrations.AlterField(
            model_name='planrecord',
            name='fortschritt_pzt_ist',
            field=models.IntegerField(default=0, verbose_name='Zielerreichungsgrad (Ist, %)'),
        ),
    ]
