# Generated by Django 5.0.7 on 2024-08-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective_manager_app', '0023_remove_planrecord_beschreibung_planrecord_kommentar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['departement_kuerzel', 'dienststelle']},
        ),
        migrations.AddField(
            model_name='strategie',
            name='titel_kurz',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Kurztitel'),
        ),
        migrations.AlterField(
            model_name='strategie',
            name='titel',
            field=models.CharField(max_length=200, verbose_name='Titel'),
        ),
    ]
