# Generated by Django 5.0.7 on 2024-10-29 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objective_manager_app', '0023_remove_planrecord_rueckmeldung_anderes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planrecord',
            name='notizen_fgs',
        ),
    ]
