# Generated by Django 5.0.7 on 2024-08-05 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective_manager_app', '0024_alter_organisation_options_strategie_titel_kurz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planrecord',
            name='bedarf_unterstuetzung',
            field=models.TextField(blank=True, null=True, verbose_name='Unterstützung'),
        ),
        migrations.AddField(
            model_name='planrecord',
            name='ergebnisse',
            field=models.TextField(blank=True, null=True, verbose_name='Ergebnisse/Erfolge'),
        ),
        migrations.AddField(
            model_name='planrecord',
            name='schwierigkeiten',
            field=models.TextField(blank=True, null=True, verbose_name='Schwierigkeiten'),
        ),
        migrations.AddField(
            model_name='planrecord',
            name='schwierigkeiten_note',
            field=models.TextField(blank=True, null=True, verbose_name='Schwierigkeiten (1-5)'),
        ),
        migrations.AddField(
            model_name='planrecord',
            name='zufriedenheit_note',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zufriedenheit (1-5)'),
        ),
        migrations.AddField(
            model_name='planrecord',
            name='zufriedenheit_text',
            field=models.TextField(blank=True, null=True, verbose_name='Zufriedenheit'),
        ),
        migrations.AlterField(
            model_name='businessobject',
            name='bestehende_massnahme',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bestehende_massnahme', to='objective_manager_app.neubestehend', verbose_name='Bestehende/Neue Massnahme'),
        ),
    ]
