# Generated by Django 5.0.7 on 2024-10-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objective_manager_app', '0024_remove_planrecord_notizen_fgs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessobject',
            old_name='jahr_ende',
            new_name='termin',
        ),
    ]
