# Generated by Django 5.0.7 on 2024-08-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective_manager_app', '0026_massnahmeorganisation_bemerkungen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massnahmeorganisation',
            name='bemerkungen',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Bemerkungen'),
        ),
    ]
