# Generated by Django 5.0.7 on 2024-08-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective_manager_app', '0027_alter_massnahmeorganisation_bemerkungen'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategiedokument',
            name='settings',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Einstellungen'),
        ),
    ]
