# Generated by Django 5.0.7 on 2024-08-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective_manager_app', '0029_remove_strategiedokument_settings_strategie_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategie',
            name='home_image',
            field=models.TextField(blank=True, null=True, verbose_name='Bildpfad'),
        ),
    ]
