# Generated by Django 5.0.7 on 2024-08-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective_manager_app', '0030_strategie_home_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessobject',
            name='mess_groesse',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Messbarkeit'),
        ),
    ]
