# Generated by Django 5.0.7 on 2024-12-22 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objective_manager_app", "0031_businessobject_mess_groesse"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wirkung",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objective_manager_app.code",),
        ),
        migrations.CreateModel(
            name="Thema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titel", models.CharField(max_length=200)),
                ("beschreibung", models.TextField(max_length=1000)),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "erstellt_von",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
