# Generated by Django 5.0.7 on 2024-12-23 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objective_manager_app", "0032_wirkung_thema"),
    ]

    operations = [
        migrations.AddField(
            model_name="thema",
            name="vorgaenger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="objective_manager_app.thema",
            ),
        ),
        migrations.AddField(
            model_name="thema",
            name="wunschrichtung",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="objective_manager_app.wirkung",
            ),
        ),
    ]
