# Generated by Django 5.0.7 on 2024-12-23 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objective_manager_app", "0033_thema_vorgaenger_thema_wunschrichtung"),
    ]

    operations = [
        migrations.AddField(
            model_name="thema",
            name="kuerzel",
            field=models.CharField(default=123, max_length=10, verbose_name="Kürzel"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="thema",
            name="wunschrichtung",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="objective_manager_app.wirkung",
                verbose_name="Erwünschte Wirkung",
            ),
        ),
    ]
