# Generated by Django 5.0.7 on 2024-12-23 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objective_manager_app", "0035_thema_sortierung"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planrecord",
            name="bedarf_unterstuetzung",
        ),
        migrations.RemoveField(
            model_name="planrecord",
            name="ergebnisse",
        ),
        migrations.RemoveField(
            model_name="planrecord",
            name="schwierigkeiten",
        ),
        migrations.RemoveField(
            model_name="planrecord",
            name="schwierigkeiten_note",
        ),
        migrations.RemoveField(
            model_name="planrecord",
            name="zufriedenheit_note",
        ),
        migrations.RemoveField(
            model_name="planrecord",
            name="zufriedenheit_text",
        ),
        migrations.CreateModel(
            name="business_object_thema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objective_manager_app.businessobject",
                    ),
                ),
                (
                    "thema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objective_manager_app.thema",
                    ),
                ),
                (
                    "wirkung",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objective_manager_app.wirkung",
                    ),
                ),
            ],
        ),
    ]
