# Generated by Django 5.0.7 on 2024-12-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "objective_manager_app",
            "0036_remove_planrecord_bedarf_unterstuetzung_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="business_object_thema",
            new_name="businessobject_thema",
        ),
    ]
