# Generated by Django 5.0.7 on 2024-12-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "objective_manager_app",
            "0037_rename_business_object_thema_businessobject_thema",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="businessobject_thema",
            new_name="BusinessobjectThema",
        ),
    ]
