# Generated by Django 5.0.7 on 2024-12-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "objective_manager_app",
            "0038_rename_businessobject_thema_businessobjectthema",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="businessobjectthema",
            name="ebene",
            field=models.IntegerField(default=1),
        ),
    ]
