# Generated by Django 5.0.7 on 2024-12-23 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objective_manager_app", "0039_businessobjectthema_ebene"),
    ]

    operations = [
        migrations.RenameField(
            model_name="planrecord",
            old_name="faellig_am",
            new_name="ende_datum",
        ),
        migrations.AddField(
            model_name="planrecord",
            name="beginn_datum",
            field=models.DateField(blank=True, null=True, verbose_name="Beginn am"),
        ),
        migrations.AddField(
            model_name="planrecord",
            name="objekt",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="objective_manager_app.businessobject",
            ),
            preserve_default=False,
        ),
    ]
