# Generated by Django 5.0.7 on 2024-12-25 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "objective_manager_app",
            "0041_remove_businessobjectthema_ebene_thema_ebene_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Kennzahl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titel", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "beschreibung",
                    models.TextField(max_length=1000, verbose_name="Beschreibung"),
                ),
                ("url", models.CharField(max_length=1000, verbose_name="URL")),
            ],
        ),
        migrations.CreateModel(
            name="BusinessObjectKennzahl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kennzahlen_business_objects",
                        to="objective_manager_app.businessobject",
                    ),
                ),
                (
                    "kennzahl",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_objects_kennzahlen",
                        to="objective_manager_app.kennzahl",
                    ),
                ),
            ],
        ),
    ]
