# Generated by Django 5.0.7 on 2024-12-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objective_manager_app", "0042_kennzahl_businessobjectkennzahl"),
    ]

    operations = [
        migrations.AddField(
            model_name="kennzahl",
            name="thema",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Thema"
            ),
        ),
        migrations.AddField(
            model_name="kennzahl",
            name="unterthema",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Thema"
            ),
        ),
    ]
